CREATE TABLE `order_project` (
  `order_project_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_project_site_id` int(10) unsigned NOT NULL,
  `order_project_idx` int(10) unsigned NOT NULL,
  `order_project_type` varchar(50) not null,
  `order_project_survey` int(2) DEFAULT NULL,
  `order_project_planning` int(2) DEFAULT NULL,
  `order_project_civil` int(2) DEFAULT NULL,
  `order_project_transport` int(2) DEFAULT NULL,
  `order_project_structural` int(2) DEFAULT NULL,
  `order_project_bridges` int(2) DEFAULT NULL,
  `order_project_utility` int(2) DEFAULT NULL,
  `order_project_water` int(2) DEFAULT NULL,
  `order_project_const` int(2) DEFAULT NULL,
  `order_project_perm` int(2) DEFAULT NULL,
  `order_project_esa` int(2) DEFAULT NULL,
  `order_project_sgc` int(2) DEFAULT NULL,
  `order_project_rap` int(2) DEFAULT NULL,
  `order_project_design_remid` int(2) DEFAULT NULL,
  `order_project_hazmat` int(2) DEFAULT NULL,
  `order_project_exp_test` int(2) DEFAULT NULL,
  `order_project_ast_ust` int(2) DEFAULT NULL,
  PRIMARY KEY (`order_project_id`, `order_project_site_id`,`order_project_type`, `order_project_survey`, `order_project_planning`, 
  `order_project_civil`, `order_project_transport`, `order_project_structural`, `order_project_bridges`, `order_project_utility`, `order_project_water`,
  `order_project_const`, `order_project_perm`, `order_project_esa`, `order_project_sgc`, `order_project_rap`, `order_project_design_remid`, `order_project_hazmat`,
  `order_project_exp_test`, `order_project_ast_ust`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;